### ISSUE TITLE
Bottomsheetdialogfragment problem

### ISSUE THREAD

**Issue by githubashutoshsoni** [SuperRabbitD/NumberPicker#8]
There is a problem in bottomsheetdialogfragment when I try to inflate. when scrolling to top the sheet minimises but it should'nt.

**Comment by eevee1502** [comment]
try this.

picker.setOnTouchListener(this);


    @Override
    public boolean onTouch(View view, MotionEvent motionEvent) {
        if(motionEvent.getAction()==MotionEvent.ACTION_DOWN && view.getId()==R.id.picker){
            setCancelable(false);
        }else if(motionEvent.getAction()==MotionEvent.ACTION_UP){
            if(!isCancelable()){
                setCancelable(true);
            }
        }
        return false;
    }
